# Site
repository: github.com/TKTheTechie
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Thomas Kunnumpurath
title: VP Of Systems Engineering - Americas @ Solace

darkmode: true

# Social links
twitter_username: TKTheTechie
github_username: TKTheTechie
linkedin_username: thomas-kunnumpurath-780a619

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Seasoned technology leader that has experience across startups, mid-size and large enterprises. I have experience building and leading both remote and on-site technology teams.

  My core leadership philosophy boils down to servant leadership. I will never ask any one of my team-mates to do something I am not willing to do and will help them along to the best of my abilities. 
  Hence, not only do I encourage my team to continuously improve but also take every opportunity to further my own education whether it be learning about a new framework, attending conferences, or getting certified on a particular technology.

  I also take a keen interest in building out technical collateral such as blog posts, white papers or longer form training content such as Udemy courses.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
#more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/', 'lib/', 'scripts/', 'docker-compose.yml']
